import NavBar from "@/components/custom/NavBar/NavBar";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div>
            <NavBar />
            <main className="flex min-h-screen flex-col items-center justify-center p-24">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
